version: "3"

services:
  mariadb:
    image: mariadb:10.9
    environment:
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal
      MARIADB_ROOT_PASSWORD: changeme
    volumes:
    - ./mariadb:/var/lib/mysql
  drupal:
    build: ./drupal
    ports:
    - "8080:80"
    volumes:
    # pre-populate volumes with:
    # docker-compose build
    # mkdir -p web/sites; mkdir -p web/modules
    # docker run --rm drupaltest-drupal:latest tar -cC /var/www/asicamera/web/sites . | tar -xC web/sites
    # docker run --rm drupaltest-drupal:latest tar -cC /var/www/asicamera/web/modules . | tar -xC web/modules
    # sudo chown -R 33:33 web/{modules,profiles,sites,themes}
    - ./web/modules:/var/www/asicamera/web/modules
    - ./web/profiles:/var/www/asicamera/web/profiles
    - ./web/sites:/var/www/asicamera/web/sites
    - ./web/themes:/var/www/asicamera/web/themes

